### ISSUE TITLE
Some Question

### ISSUE THREAD

**Issue by Godlikemandyy** [andreyryabtsev/BGMv2-webcam-plugin-linux#3]
I try to run demo_webcam.py on cpu, linux. But I get some question, eg:
OSError:[Error 22] invalid arguments
FATAL: exception not rethrown
Abolished (core saved)
I'm not sure what went wrong. Support only NVIDIA？
Looking forward to your reply！！！
Thank you！

**Comment by Rich-Lily** [comment]
Hello, I also encountered the same problem when running the script. Have you solved these problems? Looking forward to your reply!

**Comment by Godlikemandyy** [comment]
I have forgotten how to avoid it！I just want to do some tests,&nbsp;If I can't debug it well maybe I have given up！Sorry
